const USER_NOT_FOUND = 'USER_NOT_FOUND';
const USER_LOCKED = 'USER_LOCKED';
const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
const TOKEN_ID_MISSMATCH = 'TOKEN_ID_MISSMATCH';

module.exports = {
  USER_NOT_FOUND,
  USER_ALREADY_EXISTS,
  TOKEN_ID_MISSMATCH,
  USER_LOCKED,
};
